apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ping-pong-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-pong-deployment
  updatePolicy:
    updateMode: Recreate        # Apply new resources by restarting pods
  resourcePolicy:
    containerPolicies:
    - containerName: "ping-pong"   # FIXED
      minAllowed:
        cpu: 128m
        memory: 128Mi
      maxAllowed:
        cpu: 500m
        memory: 1Gi
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsAndLimits
